DECLARE
  CURSOR C_TAB IS
   SELECT TABLE_NAME
   FROM USER_TABLES
   WHERE SUBSTR(TABLE_NAME,1,2)='M_';
   V_SENTENCIA VARCHAR2(1000);
BEGIN
  FOR REG IN C_TAB LOOP
    V_SENTENCIA:='DROP TABLE '||REG.TABLE_NAME||' CASCADE CONSTRAINT PURGE';
    DBMS_OUTPUT.PUT_LINE(V_SENTENCIA);
    EXECUTE IMMEDIATE V_SENTENCIA;
  END LOOP;
END;
/